# Generated by Django 3.0.2 on 2020-01-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0003_auto_20200103_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zanr',
            name='nazev_zanru',
            field=models.CharField(max_length=80, unique=True, verbose_name='Žánr'),
        ),
    ]
