# Generated by Django 3.0.2 on 2020-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0004_auto_20200103_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zanr',
            name='nazev_zanru',
            field=models.CharField(max_length=80, verbose_name='Žánr'),
        ),
    ]
