# Generated by Django 3.0.2 on 2020-01-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0005_auto_20200103_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='info_text',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
